# Generated by Django 5.2.4 on 2025-07-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_financialyear_softwareinfo_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialyear',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
