# Generated by Django 5.2.4 on 2025-07-21 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_clientgarage_user_financial_year_clientfiscalyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgarage',
            name='currency',
            field=models.CharField(blank=True, default='NPR', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientgarage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientgarage',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='clientgarage',
            name='notifications_enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='clientgarage',
            name='whatsapp_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='softwareinfo',
            name='backup_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='softwareinfo',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV-', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='softwareinfo',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('staff', 'Staff'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('mechanic', 'Mechanic')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_categories', to='garage.clientgarage')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='garage.clientgarage')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='garage.clientgarage')),
            ],
        ),
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13.0, max_digits=5)),
                ('include_in_bill', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_settings', to='garage.clientgarage')),
            ],
        ),
    ]
