# Generated by Django 5.2.4 on 2025-07-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_clientgarage_currency_clientgarage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.clientfiscalyear'),
        ),
    ]
