# Generated by Django 5.2.4 on 2025-07-21 10:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_vehiclecompany_vehicletype_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='garage.clientgarage')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.partcategory')),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='garage.clientgarage')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='garage.clientgarage')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.vehiclecompany')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.customer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.vehiclemodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=10, unique=True)),
                ('complaint', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('waiting-assignment', 'Waiting Assignment'), ('completed', 'Completed')], default='waiting-assignment', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('entry_time', models.TimeField()),
                ('estimated_completion', models.TimeField()),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('progress', models.IntegerField(default=0)),
                ('total_so_far', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='garage.clientgarage')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.customer')),
                ('mechanics', models.ManyToManyField(limit_choices_to={'role': 'mechanic'}, to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ManyToManyField(to='garage.servicetype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Generated (In Progress)', 'Generated (In Progress)'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('items', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='garage.clientgarage')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.taxsetting')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.customer')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.serviceorder')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.vehicle')),
            ],
        ),
    ]
