# Generated by Django 5.2.4 on 2025-07-21 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_customer_part_vehicle_serviceorder_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='mechanics',
            field=models.ManyToManyField(limit_choices_to={'role': 'mechanic'}, related_name='service_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
