# Generated by Django 5.2.4 on 2025-07-21 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_alter_serviceorder_mechanics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='mechanics',
            field=models.ManyToManyField(related_name='service_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
