# Generated by Django 5.2.4 on 2025-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_alter_serviceorder_mechanics'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='helmet_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='key_given',
            field=models.BooleanField(default=False),
        ),
    ]
