# Generated by Django 5.2.4 on 2025-07-21 19:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_serviceorder_helmet_given_serviceorder_key_given'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='price',
            new_name='purchase_price',
        ),
        migrations.AddField(
            model_name='part',
            name='client_fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.clientfiscalyear'),
        ),
        migrations.AddField(
            model_name='part',
            name='last_movement',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='part',
            name='min_stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='part',
            name='movement_type',
            field=models.CharField(choices=[('added', 'Added'), ('sold', 'Sold'), ('used', 'Used')], default='added', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('in-stock', 'In Stock'), ('low-stock', 'Low Stock'), ('out-of-stock', 'Out of Stock')], default='in-stock', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='vehicle_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.vehiclecompany'),
        ),
        migrations.AddField(
            model_name='part',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='part',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.vehicletype'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash Payment'), ('credit', 'Credit Purchase'), ('advance', 'Advance Payment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.clientfiscalyear')),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='garage.clientgarage')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.part')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='garage.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('lubricants', 'Lubricants'), ('spare-parts', 'Spare Parts'), ('drive-train', 'Drive Train'), ('electrical', 'Electrical'), ('tools', 'Tools & Equipment')], max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate'), ('7-days', '7 Days'), ('15-days', '15 Days'), ('30-days', '30 Days'), ('45-days', '45 Days'), ('60-days', '60 Days')], default='30-days', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.clientfiscalyear')),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='garage.clientgarage')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='garage.supplier'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='garage.clientgarage')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='garage.supplier')),
            ],
        ),
    ]
