# Generated by Django 5.2.4 on 2025-07-23 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_rename_price_part_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(default='fa-motorcycle', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='garage.clientgarage')),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='garage.bill')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garage.item')),
            ],
        ),
    ]
