# Generated by Django 5.2.4 on 2025-07-23 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0013_bill_credit_amount_bill_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='garage.part'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
