# Generated by Django 5.2.4 on 2025-07-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0014_alter_billitem_item_alter_billitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='garage.serviceorder')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.servicetype')),
            ],
            options={
                'db_table': 'garage_serviceorderitem',
            },
        ),
    ]
