# Generated by Django 5.2.4 on 2025-07-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0016_alter_bill_service_order_alter_bill_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
